# Generated by Django 3.1.4 on 2021-04-30 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails_razorpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=256, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails_paytm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TXNID', models.CharField(max_length=500, unique=True)),
                ('BANKTXNID', models.CharField(max_length=500)),
                ('ORDERID', models.CharField(max_length=255)),
                ('TXNAMOUNT', models.FloatField()),
                ('STATUS', models.CharField(max_length=100)),
                ('TXNTYPE', models.CharField(max_length=100)),
                ('GATEWAYNAME', models.CharField(max_length=100)),
                ('RESPCODE', models.CharField(max_length=100)),
                ('RESPMSG', models.CharField(max_length=100)),
                ('BANKNAME', models.CharField(max_length=255)),
                ('MID', models.CharField(max_length=500)),
                ('PAYMENTMODE', models.CharField(max_length=100)),
                ('REFUNDAMT', models.FloatField()),
                ('TXNDATE', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails_paypal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(max_length=200)),
                ('payerID', models.CharField(max_length=200)),
                ('paymentID', models.CharField(max_length=500)),
                ('billingToken', models.CharField(max_length=500)),
                ('facilitatorAccessToken', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
