# Generated by Django 3.1.4 on 2021-04-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block_printing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=500)),
                ('answer1', models.CharField(max_length=350)),
                ('image1', models.ImageField(upload_to='pics')),
                ('question2', models.CharField(default=None, max_length=500, null=True)),
                ('answer2', models.CharField(default=None, max_length=5000, null=True)),
                ('image2', models.ImageField(default=None, null=True, upload_to='pics')),
                ('page_number', models.IntegerField(unique=True)),
            ],
        ),
    ]
