# Generated by Django 3.1.4 on 2021-05-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThumkiStores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='img',
            field=models.ImageField(upload_to='Thumki/static/images/pics'),
        ),
    ]
