# Generated by Django 3.1.4 on 2021-05-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThumkiStores', '0002_auto_20210501_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='Thumki/static/images/pics/categories'),
        ),
        migrations.AlterField(
            model_name='general_info',
            name='fav_icon',
            field=models.ImageField(upload_to='Thumki/static/images/pics'),
        ),
        migrations.AlterField(
            model_name='general_info',
            name='image',
            field=models.ImageField(upload_to='Thumki/static/images/pics'),
        ),
    ]
